### ISSUE TITLE
Tool Is Non-Functioning

### ISSUE THREAD

**Issue by SatansFavSuccubus** [kakaroto/ps3xport#22]
None of the commands work. Both CMd & PowerShell tell me there are no ".configure" or "./ps3xport" commands. Absolutely none of the commands work. This program is defunct. :( I was really hoping to be able to finally decrypt some Archive.dat files so I can get my game data but man... None of these PS3 Backup/Extract/Decryption tools work. **They are ALL broken.**

:'(

Using the latest build, unfortunately.

![image](https://user-images.githubusercontent.com/88169925/127580666-2c70b823-b284-496c-abba-b3edbb5a0c12.png)

![image](https://user-images.githubusercontent.com/88169925/127580730-4503558d-5ab7-41a8-b051-f8defc33e231.png)

**Comment by kakaroto** [comment]
That's because those are Linux commands.
Also, I do not support this tool anymore, it hasn't been touched in 6 years.

**Comment by SatansFavSuccubus** [comment]
Then how am I supposed to decrypt/extract files form my Archive.dat files? No other program even touches on that... Is there any other tool that can decrypt these files?
