### ISSUE TITLE
Issue with documentation

### ISSUE THREAD

**Issue by philou-felin** [kakaroto/ps3xport#23]
Hi!

The readme mentions a "keys.conf" file, but it doesn't give much information as to how we can get the file. Do we need another tool to create the file, or is it somewhere in the PS3? I already have MultiMAN in my PS3, so maybe this can help.

I think I got that I need to create the file. (I read that: https://kakaroto.ca/2014/12/ps3xport-released/) In that case, what does that sentence mean: "The keys.conf file needs to have a key of type 'sc' with revision 3." I never wrote a ".conf" file before.

**Comment by kakaroto** [comment]
The keys cannot be distributed for legal reasons. 
You can get a lot of information about them on this page: https://www.psdevwiki.com/ps3/Keys

Google is also your friend: https://www.google.com/search?q=ps3+keys.conf
I don't work on this project anymore and therefore have no plans on updating its README or doing any work on it anymore.

**Comment by philou-felin** [comment]
Sorry for re-opening, but I'm doing it only to thank you very much for your hard work! 😃 You can close it again now. 😅
