### ISSUE TITLE
Windows port: ExtractFile pulls out the wrong data

### ISSUE THREAD

**Issue by Asure** [kakaroto/ps3xport#3]
Using the windows version, with the ExtractFile command and a proper idps / psid.

Command line example:

%1=path to the hdd backup.

ps3xport.exe ExtractPSID %1 psid.bin SetPSID ./psid.bin SetDeviceID ./idps.bin ExtractFile %1 /dev_hdd0/home/00000027/exdata/UP0555-NPUB30067_00-NECTARISPURCHASE.edat UP0555-NPUB30067_00-NECTARISPURCHASE.edat

ps3xport.exe ExtractPSID %1 psid.bin SetPSID ./psid.bin SetDeviceID ./idps.bin ExtractFile %1 /dev_hdd0/home/00000027/exdata/UP0006-NPUB30454_00-GATLINGGEARSUNLK.edat UP0006-NPUB30454_00-GATLINGGEARSUNLK.edat

This pulls out two files of 352 bytes, with the exact same content.
The 352 bytes are from the same 'object'
If you pull out a larger file, say act.dat, you get 4152 bytes from the same object.
(Meaning the first 352 bytes match with any of the previously pulled edat files.)
It seems the content from the encrypted dump is not read correctly, or not written correctly.

The object it is reading might be history file, or pushlist, i cannot tell for sure, i am not an expert.
It starts with a list of tiles (33 titles, example NPEB00515), then the title followed by the version (NPEB00515 01.00 for example) and then a few links of media files from poseidon.dl.playstation.net.

I will not post the entire file because of privacy reasons.

Duplicate the issue:
1. Use windows
2. Dump a small file from idps-encrypted archive
3. Dump a big file from the idps-encrypted archve.
4. Compare content, notice the matching data, and invalid contents of the files.

**Comment by noowe** [comment]
Hey guys. Im pretty noobish at this since im new.. so my question is how do i open this commands lists? with wich program? is it only for Linux computer or is it any special program? i really can't find out :/ sorry for the noobish question
